"""Integration tests: permissions (WP9), skills (WP5), postmortems (WP6),
evolution rollback (WP10), scaffold composition (WP4)."""

import shutil
import sys
from pathlib import Path

import pytest

HARNESS_ROOT = Path(__file__).resolve().parent.parent
SEEDS = HARNESS_ROOT / "seeds"


@pytest.fixture
def project(tmp_path, run_py):
    """A minimal generated-project skeleton with orchestrator + seeds."""
    root = tmp_path / "project"
    for d in ("memory", "constraints", "tools", "evolution"):
        (root / d).mkdir(parents=True)
    shutil.copy2(SEEDS / "orchestrator.py", root / "orchestrator.py")
    shutil.copy2(SEEDS / "guard.py", root / "guard.py")
    shutil.copy2(SEEDS / "memory" / "event-log.yaml", root / "memory" / "event-log.yaml")
    shutil.copy2(SEEDS / "tools" / "permissions.yaml", root / "tools" / "permissions.yaml")
    shutil.copy2(SEEDS / "tools" / "enforce-permission.py", root / "tools" / "enforce-permission.py")
    (root / "task.yaml").write_text(
        "name: P\ngoal: G\nacceptance_criteria: [AC1 works]\n", encoding="utf-8")
    return root


# ---------------------------------------------------------------- WP9 permissions

def test_permission_chain_allow_and_deny(project, run_py):
    run_py(project, "orchestrator.py", "--status")
    code, out = run_py(project, "guard.py", "--permission", "read-only", "--check",
                       "implement the login endpoint in src with input validation")
    assert code == 0 and "ALLOWED" in out
    code, out = run_py(project, "guard.py", "--permission", "read-only", "--check",
                       "I plan to run npm install then git push")
    assert code == 126 and "DENIED" in out


def test_permission_unknown_mode_rejected(project, run_py):
    run_py(project, "orchestrator.py", "--status")
    # argparse rejects an unknown mode up front (fail-closed, exit != 0)
    code, out = run_py(project, "guard.py", "--permission", "bogus", "--check", "x")
    assert code != 0 and "invalid choice" in out


def test_enforce_permission_exit_code_separation(project, run_py):
    code, out = run_py(project, "tools/enforce-permission.py", "--mode", "read-only",
                       "--", sys.executable, "-c", "print('hi')")
    assert code == 0
    code, out = run_py(project, "tools/enforce-permission.py", "--mode", "read-only",
                       "--", "pip", "install", "flask")
    assert code == 126 and "PERMISSION_DENIED" in out
    # task failure is NOT a permission denial
    code, out = run_py(project, "tools/enforce-permission.py", "--mode", "full",
                       "--", sys.executable, "-c", "import sys; sys.exit(3)")
    assert code == 3


# ---------------------------------------------------------------- WP5 skills

def test_skill_catalog_list_and_load(project, run_py):
    skills_dir = project / "skills"
    skills_dir.mkdir()
    (skills_dir / "systematic-debugging.md").write_text(
        "# Systematic Debugging\n\nRoot cause first.\n", encoding="utf-8")
    (skills_dir / "tdd.md").write_text("# TDD\n\nWrite tests first.\n", encoding="utf-8")
    # catalog generated by scaffold in real projects; test the loader directly
    catalog = {"version": 1, "complete": True, "skills": [
        {"id": "systematic-debugging", "name": "Systematic Debugging",
         "description": "Root cause first.", "path": "skills/systematic-debugging.md"},
        {"id": "tdd", "name": "TDD", "description": "Write tests first.",
         "path": "skills/tdd.md"},
    ]}
    import yaml
    (skills_dir / "catalog.yaml").write_text(yaml.dump(catalog), encoding="utf-8")

    code, out = run_py(project.parent, str(HARNESS_ROOT / "seeds" / "context" / "loader.py"),
                       "skill", "list", "--project-root", str(project))
    assert code == 0 and "systematic-debugging" in out
    code, out = run_py(project.parent, str(HARNESS_ROOT / "seeds" / "context" / "loader.py"),
                       "skill", "load", "tdd", "--project-root", str(project))
    assert code == 0 and "Write tests first" in out
    code, out = run_py(project.parent, str(HARNESS_ROOT / "seeds" / "context" / "loader.py"),
                       "skill", "load", "nope", "--project-root", str(project))
    assert code == 2 and "unknown skill" in out


def test_skill_broken_listed_with_reason(project, run_py):
    skills_dir = project / "skills"
    skills_dir.mkdir()
    import yaml
    catalog = {"version": 1, "complete": True, "skills": [
        {"id": "ghost", "name": "Ghost", "description": "",
         "path": "skills/ghost.md"}]}
    (skills_dir / "catalog.yaml").write_text(yaml.dump(catalog), encoding="utf-8")
    code, out = run_py(project.parent, str(HARNESS_ROOT / "seeds" / "context" / "loader.py"),
                       "skill", "list", "--project-root", str(project))
    assert "BROKEN" in out and "ghost" in out


# ---------------------------------------------------------------- WP6 postmortems

def test_postmortem_written_and_idempotent(project, run_py):
    (project / "memory" / "meta-mistakes.md").write_text(
        "## Meta-Mistake 1\nStatus: Open\nRoot Cause: hash collisions\n"
        "Lesson: verify hashes before writing\n", encoding="utf-8")
    (project / "constraints" / "architecture-rules.yaml").write_text(
        "version: 1\nrules: []\n", encoding="utf-8")
    script = HARNESS_ROOT / "seeds" / "feedback" / "mistake-to-constraint.py"
    args = ["--mistakes-file", "memory/meta-mistakes.md",
            "--constraints-file", "constraints/architecture-rules.yaml",
            "--project-root", str(project)]
    code, out = run_py(project, str(script), *args)
    assert code == 0
    postmortems = list((project / "memory" / "postmortems").glob("*.md"))
    assert len(postmortems) == 1
    text = postmortems[0].read_text(encoding="utf-8")
    assert "Root cause" in text and "Why it escaped" in text
    # event log records the mistake
    log = (project / "memory" / "event-log.yaml").read_text(encoding="utf-8")
    assert "mistake/recorded" in log
    # idempotent: re-running does not duplicate
    code, _ = run_py(project, str(script), *args)
    assert len(list((project / "memory" / "postmortems").glob("*.md"))) == 1


# ---------------------------------------------------------------- WP10 evolution

def test_evolution_approval_tier_snapshot_rollback(project, run_py):
    (project / "evolution" / "genome.yaml").write_text(
        "version: 1\ntotal_mutations: 0\nlast_evolved: '2026-01-01T00:00:00'\n"
        "harness_genome:\n  constraints:\n"
        + "".join(f"    - {{id: C{i:03d}, rule: 'r{i}', trigger_count: 0}}\n" for i in range(1, 7))
        + "  skills: []\n  workflows: []\n", encoding="utf-8")
    (project / "memory" / "meta-mistakes.md").write_text(
        "\n".join(f"## Meta-Mistake {i}\nStatus: Open\nRoot Cause: cause{i}\n"
                  for i in range(1, 5)), encoding="utf-8")
    script = HARNESS_ROOT / "scripts" / "evolve.py"
    code, out = run_py(project, str(script), "--project-root", str(project))
    assert code == 0
    assert "ACCEPTED" in out
    import yaml
    genome = yaml.safe_load((project / "evolution" / "genome.yaml").read_text(encoding="utf-8"))
    assert len(genome["harness_genome"]["constraints"]) == 7  # ADD_CONSTRAINT applied
    assert genome.get("version") == 2  # versioned generation
    assert len(genome.get("generations", [])) == 1
    snapshots = list((project / "evolution" / "snapshots").glob("genome-*.yaml"))
    assert len(snapshots) == 1
    log = yaml.safe_load((project / "evolution" / "log.yaml").read_text(encoding="utf-8"))
    entry = log["mutations"][0]
    assert entry.get("approval") == "AUTO"
    assert entry.get("evidence_refs")
    assert entry.get("rollback")  # reversible command recorded
    # rollback restores the pre-mutation genome
    code, out = run_py(project, str(script), "--project-root", str(project), "--rollback")
    assert code == 0
    genome = yaml.safe_load((project / "evolution" / "genome.yaml").read_text(encoding="utf-8"))
    assert len(genome["harness_genome"]["constraints"]) == 6


# ---------------------------------------------------------------- WP4 composition

def test_scaffold_emits_composition_and_patch_gates(meta_root, run_py):
    import yaml
    task = meta_root / "task.yaml"
    task.write_text(
        "name: T\ndomain: api_service\ngoal: G\nacceptance_criteria: [a]\n"
        "complexity: {S: 3, C: 3, N: 3, K: 3, tier: standard}\n", encoding="utf-8")
    code, out = run_py(meta_root, str(HARNESS_ROOT / "scripts" / "scaffold.py"),
                       "--task", str(task), "--output", str(meta_root / "gen"))
    assert code == 0
    comp = meta_root / "gen" / "harness-composition.yaml"
    assert comp.exists()
    doc = yaml.safe_load(comp.read_text(encoding="utf-8"))
    rows = doc["rows"]
    ids = [r["id"] for r in rows]
    assert "guard.py" in ids and "context/knowledge-index.yaml" in ids
    assert any(r["id"] == "verification/self-check.py" and r.get("runner") == "orchestrator"
               for r in rows)
    # unknown patch id fails compose (fail-closed)
    patch = meta_root / "gen" / "harness-patch.yaml"
    patch.write_text("version: 1\nrows:\n  - {id: nope/x.py, enabled: false}\n",
                     encoding="utf-8")
    import subprocess
    import sys
    proc = subprocess.run(
        [sys.executable, str(HARNESS_ROOT / "scripts" / "compose.py"),
         "--composition", str(comp), "--patch", str(patch)],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    assert proc.returncode == 1 and "unknown row id" in proc.stderr
